carts/urls.py
from django.urls import path
from .views import (
    cart_home,
    cart_update,
    checkout_home,
    checkout_done_view,
    cart_detail_api_view,
)

app_name = "carts"

urlpatterns = [
    path("", cart_home, name="home"),
    path("api/", cart_detail_api_view, name="home_api"),
    path("checkout/", checkout_home, name="checkout"),
    path("update/", cart_update, name="update"),
    path("success/<str:order_code>/<int:products>/", checkout_done_view, name="success"),
]

crpasite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import home_page, termandconds_page
from taxcategs.views import taxonomy_view


urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("", home_page, name="home_url"),
        path("termandconds", termandconds_page, name="termandconds_url"),
        path("accounts/", include("accounts.urls")),
        path("products/", include("products.urls"), name="products"),
        path("addresses/", include("addresses.urls")),
        path("cart/", include("carts.urls")),
        path("search/", include("search.urls")),
        path("categories/", include("taxcategs.urls")),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

carts/models.py
from django.conf import settings
from django.db import models
from products.models import Product
from django.db.models.signals import pre_save, m2m_changed
from decimal import Decimal

User = settings.AUTH_USER_MODEL


class CartManager(models.Manager):
    def new_or_get(self, request):
        cart_id = request.session.get("cart_id", None)
        qs = self.get_queryset().filter(id=cart_id)
        if qs.count() == 1:
            new_obj = False
            cart_obj = qs.first()
            if request.user.is_authenticated and cart_obj.user is None:
                cart_obj.user = request.user
                cart_obj.save()
        else:
            cart_obj = self.new(user=request.user)
            new_obj = True
            request.session["cart_id"] = cart_obj.id
        return cart_obj, new_obj

    def new(self, user=None):
        user_obj = None
        if user is not None:
            if user.is_authenticated:
                user_obj = user
        return self.model.objects.create(user=user_obj)


class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    products = models.ManyToManyField(Product, blank=True)
    subtotal = models.DecimalField(max_digits=30, decimal_places=4, default=0)
    total = models.DecimalField(max_digits=30, decimal_places=4, default=0)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    objects = CartManager()

    def __str__(self):
        return str(self.id)


def m2m_changed_cart_receiver(sender, instance, action, *args, **kwargs):
    if action == "post_add" or action == "post_remove" or action == "post_clear":
        products = instance.products.all()
        total = 0
        for x in products:
            total += x.price
        if instance.subtotal != total:
            instance.subtotal = total
            instance.save()


m2m_changed.connect(m2m_changed_cart_receiver, sender=Cart.products.through)


def pre_save_cart_receiver(sender, instance, *args, **kwargs):
    if instance.subtotal > 0:
        instance.total = Decimal(instance.subtotal) * Decimal(1.08)
    else:
        instance.total = 0


pre_save.connect(pre_save_cart_receiver, sender=Cart)

carts/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from products.models import Product, ProductsAvailable
from .models import Cart
from orders.models import Order
from accounts.forms import LoginForm, GuestForm
from billing.models import BillingProfile
from addresses.forms import AddressForm
from addresses.models import Address
from decimal import Decimal
from django.http import HttpResponseRedirect
from django.contrib import messages


def cart_detail_api_view(request):
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    products = [
        {
            "id": x.id,
            "url": x.get_absolute_url(),
            "title": x.title,
            "price": format(x.price, ".2f"),
        }
        for x in cart_obj.products.all()
    ]
    cart_data = {
        "products": products,
        "subTotal": format(cart_obj.subtotal, ".2f"),
        "total": format(cart_obj.total, ".2f"),
    }
    return JsonResponse(cart_data, status=200)


def cart_home(request):
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    return render(request, "carts/home.html", {"cart": cart_obj})


def cart_update(request):
    product_id = request.POST.get("product_id")
    if product_id is not None:

        # get product or return cart page
        try:
            product_obj = Product.objects.get(id=product_id)
        except Product.DoesNotExist:
            # ajax error response
            if request.is_ajax():
                json_data = {
                    "added": False,
                    "removed": False,
                }
                return JsonResponse(json_data, status=409)

            return redirect("carts:home")

        cart_obj, new_obj = Cart.objects.new_or_get(request)

        if product_obj in cart_obj.products.all():
            # remove product cart
            cart_obj.products.remove(product_obj)
            product_added = False
        else:
            # add product cart
            cart_obj.products.add(product_obj)
            product_added = True

        # cart product count update
        request.session["cart_items"] = cart_obj.products.count()

        if request.is_ajax():
            json_data = {
                "added": product_added,
                "removed": not product_added,
                "cartItemCount": cart_obj.products.count(),
            }
            return JsonResponse(json_data, status=200)

    # no product_id in post request
    return redirect("carts:home")


def checkout_home(request):
    cart_obj, cart_created = Cart.objects.new_or_get(request)
    order_obj = None
    billing_address_id = request.session.get("billing_address_id", None)
    shipping_address_id = request.session.get("shipping_address_id", None)

    if cart_created or cart_obj.products.count() == 0:
        return redirect("carts:home")

    billing_profile, billing_profile_created = BillingProfile.objects.new_or_get(
        request
    )
    address_qs = None
    if billing_profile is not None:
        if request.user.is_authenticated:
            address_qs = Address.objects.filter(billing_profile=billing_profile).all().distinct("address_line_1", "postal_code")
        order_obj, order_obj_created = Order.objects.new_or_get(
            billing_profile, cart_obj
        )

        if shipping_address_id:
            order_obj.shipping_address = Address.objects.get(id=shipping_address_id)
            del request.session["shipping_address_id"]
        if billing_address_id:
            order_obj.billing_address = Address.objects.get(id=billing_address_id)
            del request.session["billing_address_id"]
        if billing_address_id or shipping_address_id:
            order_obj.save()

    if request.method == "POST":
        "some check that order is done"
        is_done = order_obj.check_done()
        if request.user.is_authenticated:
            user = request.user
        for produuuuuct in cart_obj.products.all():
            if produuuuuct.user.pk == user.pk:
                messages.warning(request, "Cannot buy one of your products")
                return render(request, "carts/home.html", {})
        if is_done:
            order_obj.mark_paid()
            # Add product to available list
            if ProductsAvailable.objects.filter(user=user).exists():
                p = ProductsAvailable.objects.get(user=user)
                p.products.add(*cart_obj.products.all())
            else:
                p = ProductsAvailable.objects.create(user=user)
                p.products.add(*cart_obj.products.all())
            del request.session["cart_id"] 
            return HttpResponseRedirect(reverse("carts:success", kwargs={"order_code": order_obj.order_code, "products": p.pk}))

    context = {
        "object": order_obj,
        "billing_profile": billing_profile,
        "login_form": LoginForm(),
        "guest_form": GuestForm(),
        "address_form": AddressForm(),
        "address_qs": address_qs,
    }

    return render(request, "carts/checkout.html", context)


def checkout_done_view(request, **kwargs):
    prods = ProductsAvailable.objects.get(pk=kwargs["products"])
    context = {"order_code": kwargs["order_code"], "products": prods.products.all()}
    return render(request, "carts/checkout-done.html", context)

templates/carts/snippets/cart-ajax.html
<script>
    $(document).ready(function () {
        let productForm = $('.form-product-ajax');
        productForm.submit(function (e) {
            e.preventDefault();
            let thisForm = $(this);
            let actionEndPoint = thisForm.attr('action');
            let httpMethod = thisForm.attr('method');
            let formData = thisForm.serialize();

            $.ajax({
                url: actionEndPoint,
                method: httpMethod,
                data: formData,
                success: function (data) {
                    let submitSpan = thisForm.find('.submit-span');
                    if (data.added && data.removed === false) {
                        submitSpan.html(
                            '<p>In Cart</p> <button type="submit" class="btn_3">Remove ?</button>'
                        );
                    }
                    if (data.removed && data.added === false) {
                        submitSpan.html(
                            '<button type="submit" class="btn_3">Add to cart</button>'
                        );
                    }
                    let navCount = $('.nav-cart-count');
                    navCount.html(data.cartItemCount + '<i class="fas fa-shopping-cart">');

                    let currentPath = window.location.href;

                    if (currentPath.indexOf('cart') !== -1) {
                        refreshCart();
                    }
                },
                error: function (errorData) {
                    $.alert({
                        title: 'Oops !',
                        content: errorData,
                        theme: 'modern',
                    });
                }
            });

            function refreshCart() {
                let currentUrl = window.location.href;
                let cartTable = $('.cart-table');
                let cartBody = cartTable.find('.cart-body');
                let productRows = cartBody.find('.cart-products');

                let refreshCartUrl = thisForm.attr('data-endpoint');
                let refreshCartMethod = 'GET';
                let data;

                $.ajax({
                    url: refreshCartUrl,
                    method: refreshCartMethod,
                    data: data,
                    success: function (data) {

                        let hiddenCartItemForm = $('.cart-item-remove-form');

                        if (data.products.length > 0) {
                            productRows.html("");
                            let i = 1;
                            $.each(data.products, function (index, value) {
                                let newCartItemRemove = hiddenCartItemForm.clone();
                                newCartItemRemove.css('display', 'block');
                                newCartItemRemove.find('.cart-item-product-id').val(
                                    value.id);

                                cartBody.prepend('<th scope="row">' + i +
                                    '</th>\n' +
                                    '<td><a href="' + value.url + '">' + value
                                    .title + '</a></td>\n' +
                                    '<td>' + value.price + '</td>' +
                                    '<td>' + newCartItemRemove.html() + '</td>');
                                i++;
                            });
                            cartBody.find('.cart-subTotal').text(data.subTotal);
                            cartBody.find('.cart-total').text(data.total);
                        } else {
                            window.location.href = currentUrl;
                        }
                    },
                    error: function (errorData) {
                        $.alert({
                            title: 'Oops !',
                            content: errorData,
                            theme: 'modern',
                        });
                    }
                });
            }
        });
    });
</script>

templates/carts/snippets/remove-product.html
<form class="form form-product-ajax" method="POST" action="{% url 'carts:update' %}"
  data-endpoint="{% url 'carts:home_api' %}">
  {% csrf_token %}
  <input class="cart-item-product-id" type="hidden" name="product_id" value="{{ product_id }}">
  <button type="submit" class="genric-btn danger-border circle">Remove</button>
</form>