accounts/urls.py
from django.urls import path
from .views import login_page, register_page, guest_register_view, register_page_reviewer, AccountDetailView, destroy
from django.contrib.auth.views import LogoutView

app_name = "accounts"

urlpatterns = [
    path("login/", login_page, name="login"),
    path("register/", register_page, name="register"),
    path("view/", AccountDetailView.as_view(), name="view"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("guest/register/", guest_register_view, name="guest_register"),
    path("reviewer/register/", register_page_reviewer, name="reviewer_register"),
    path("delete/", destroy, name="delete"),
]

carts/urls.py
from django.urls import path
from .views import (
    cart_home,
    cart_update,
    checkout_home,
    checkout_done_view,
    cart_detail_api_view,
)

app_name = "carts"

urlpatterns = [
    path("", cart_home, name="home"),
    path("api/", cart_detail_api_view, name="home_api"),
    path("checkout/", checkout_home, name="checkout"),
    path("update/", cart_update, name="update"),
    path("success/<str:order_code>/<int:products>/", checkout_done_view, name="success"),
]

crpasite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import home_page, termandconds_page
from taxcategs.views import taxonomy_view


urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("", home_page, name="home_url"),
        path("termandconds", termandconds_page, name="termandconds_url"),
        path("accounts/", include("accounts.urls")),
        path("products/", include("products.urls"), name="products"),
        path("addresses/", include("addresses.urls")),
        path("cart/", include("carts.urls")),
        path("search/", include("search.urls")),
        path("categories/", include("taxcategs.urls")),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

accounts/models.py
from django.db import models
from django.contrib.auth.models import (
    AbstractBaseUser,
    BaseUserManager,
    PermissionsMixin,
)

class UserManager(BaseUserManager):
    def create_user(
        self,
        email,
        password=None,
        first_name=None,
        last_name=None,
        role=None,
        is_active=True,
        is_staff=False,
        is_superuser=False,
    ):
        if not email:
            raise ValueError("Users must have an email address")
        if not password:
            raise ValueError("Users must have a password")

        user_obj = self.model(
            email=self.normalize_email(email),
            first_name=first_name,
            last_name=last_name,
            role = role,
        )
        user_obj.active = is_active
        user_obj.staff = is_staff
        user_obj.superuser = is_superuser
        user_obj.set_password(password)  # change user password
        user_obj.save(using=self._db)
        return user_obj

    def create_staff_user(self, email, password=None):
        user_obj = self.create_user(email, password=password, is_staff=True)
        return user_obj

    def create_superuser(self, email, password=None):
        user_obj = self.create_user(
            email, password=password, role=4, is_staff=True, is_superuser=True
        )
        return user_obj

REVIEWER = 1
PROVIDER = 2
DEVELOPER = 3
ADMIN = 4

class User(AbstractBaseUser, PermissionsMixin):
    ROLE_CHOICES = (
        (REVIEWER, "Reviewer"),
        (PROVIDER, "Provider"),
        (DEVELOPER, "Developer"),
        (ADMIN, "Administrator"),
    )
    role = models.PositiveSmallIntegerField(choices=ROLE_CHOICES, default = 3)
    email = models.EmailField(
        null=False, blank=False, unique=True, max_length=80, verbose_name="Email"
    )
    first_name = models.CharField(
        null=True, blank=True, max_length=80, verbose_name="First Name"
    )
    last_name = models.CharField(
        null=True, blank=True, max_length=80, verbose_name="Last Name"
    )
    active = models.BooleanField(default=True, verbose_name="Is Active")
    staff = models.BooleanField(default=False, verbose_name="Is Staff")
    superuser = models.BooleanField(default=False, verbose_name="Is Super User")

    USERNAME_FIELD = "email"  # username
    # USERNAME_FIELD and password are required by default
    REQUIRED_FIELDS = []  # python manage.py createsuperuser

    objects = UserManager()

    def __str__(self):
        return self.email

    def get_short_name(self):
        if self.first_name:
            return self.first_name
        return self.email

    def get_full_name(self):
        if self.first_name and self.last_name:
            return f"{self.first_name} {self.last_name}"
        return self.email

    @property
    def is_active(self):
        return self.active

    @property
    def is_staff(self):
        return self.staff

    @property
    def is_superuser(self):
        return self.superuser


class GuestEmail(models.Model):
    email = models.EmailField()
    active = models.BooleanField(default=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.email

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import ReadOnlyPasswordHashField

User = get_user_model()


class UserAdminCreationForm(forms.ModelForm):
    """
    A form for creating new users. Includes all the required
    fields, plus a repeated password.
    """

    password1 = forms.CharField(label="Password", widget=forms.PasswordInput)
    password2 = forms.CharField(
        label="Password confirmation", widget=forms.PasswordInput
    )

    class Meta:
        model = User
        fields = ("email",)

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(UserAdminCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserAdminChangeForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    """

    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ("email", "password", "active", "superuser")

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]


class LoginForm(forms.Form):
    email = forms.CharField(
        widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "E-Mail"})
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={"class": "form-control", "placeholder": "Password"}
        )
    )


class RegisterForm(forms.Form):
    first_name = forms.CharField(
        label="First Name",
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "First Name"}
        ),
    )
    last_name = forms.CharField(
        label="Last Name",
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "Last Name"}
        ),
    )
    email = forms.EmailField(
        widget=forms.EmailInput(attrs={"class": "form-control", "placeholder": "Email"})
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={"class": "form-control", "placeholder": "Password"}
        )
    )
    password2 = forms.CharField(
        label="Confirm Password",
        widget=forms.PasswordInput(
            attrs={"class": "form-control", "placeholder": "Password again"}
        ),
    )
    role = forms.ChoiceField(choices=(
        (2, "Provider"),
        (3, "Developer"),
    ), widget = forms.Select(attrs={"class": "form-control"}),
    )

    def clean_email(self):
        email = self.cleaned_data.get("email")
        qs = User.objects.filter(email=email)
        if qs.exists():
            raise forms.ValidationError("Email is taken")
        return email

    def clean(self):
        data = self.cleaned_data
        password = data.get("password")
        password2 = data.get("password2")
        if password2 != password:
            raise forms.ValidationError("Passwords must match")
        return data


class GuestForm(forms.Form):
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={"class": "form-control", "placeholder": "Your Email"}
        )
    )

class DeactivateUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['active']

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import get_user_model, authenticate, login
from .forms import RegisterForm, LoginForm, GuestForm
from django.views.generic import DetailView
from .models import GuestEmail
from django.utils.http import is_safe_url
from django.contrib import messages
from django.urls import reverse
from django.shortcuts import HttpResponseRedirect
from django.urls import reverse_lazy

User = get_user_model()


def register_page(request):
    form = RegisterForm(request.POST or None)

    if form.is_valid():
        data = form.cleaned_data
        role = data.get("role")
        # Checking: user cannot register as Reviewer
        if role == "2" or role == "3":
            password = data.get("password")
            first_name = data.get("first_name")
            last_name = data.get("last_name")
            email = data.get("email")
            new_user = User.objects.create_user(
                email, password, first_name, last_name, int(role)
            )
        else:
            new_user = None
        if new_user is not None:
            messages.success(request, "Created User.")
            return redirect("accounts:login")

        messages.warning(request, "Create Error !")

    context = {"form": form}

    return render(request, "accounts/register.html", context)


def register_page_reviewer(request):
    form = RegisterForm(request.POST or None)

    if form.is_valid():
        data = form.cleaned_data
        # Checking: user cannot create a Reviewer account, only Reviewers can create others Reviewers accounts
        if request.user.is_authenticated and (request.user.role == 1):
            password = data.get("password")
            first_name = data.get("first_name")
            last_name = data.get("last_name")
            email = data.get("email")
            role = "1"
            new_user = User.objects.create_user(
                email, password, first_name, last_name, int(role)
            )
        else:
            new_user = None
        if new_user is not None:
            messages.success(request, "Reviewer created.")
            return redirect("accounts:reviewer_register")

        messages.warning(request, "Create Error !")

    context = {"form": form}

    return render(request, "accounts/register_reviewer.html", context)


def login_page(request):
    if request.user.is_authenticated:
        return redirect("home_url")

    form = LoginForm(request.POST or None)
    context = {"form": form}
    next_ = request.GET.get("next")
    next_post = request.POST.get("next")
    redirect_path = next_ or next_post or None

    if form.is_valid():
        data = form.cleaned_data
        email = data.get("email")
        password = data.get("password")
        user = authenticate(request, email=email, password=password)
        if user is not None:
            login(request, user)
            try:
                del request.session["guest_email_id"]
            except:
                pass
            if is_safe_url(redirect_path, request.get_host()):
                return redirect(redirect_path)
            else:
                return redirect("home_url")
        else:
            messages.warning(request, "Credentials error.")

    return render(request, "accounts/login.html", context)


def guest_register_view(request):
    if request.user.is_authenticated:
        return redirect("carts:home")

    form = GuestForm(request.POST or None)
    context = {"form": form}
    next_ = request.GET.get("next")
    next_post = request.POST.get("next")
    redirect_path = next_ or next_post or None

    if form.is_valid():
        data = form.cleaned_data
        email = data.get("email")
        new_guest_email = GuestEmail.objects.create(email=email)
        request.session["guest_email_id"] = new_guest_email.id
        if is_safe_url(redirect_path, request.get_host()):
            return redirect(redirect_path)
        else:
            return redirect("home_url")

    return render(request, "accounts/login.html", context)

 
class AccountDetailView(DetailView):
    def get(self, request, *args, **kwargs):
        roles = {"1":"Reviewer","2":"Provider","3":"Developer","4":"Administrador"}
        if self.request.user.is_authenticated:
            user = get_object_or_404(User, pk=request.user.pk)
        else:
            user = None
        rol = roles.get(str(user.role))
        context = {'user': user, 'rol': rol}
        return render(request, 'accounts/detail.html', context)


def destroy(request):
    User.objects.filter(pk=request.user.id).update(active=False)
    messages.warning(request, "Deleted User.")
    return HttpResponseRedirect(reverse_lazy('accounts:logout')) 

templates/accounts/detail.html
{% extends 'base.html' %}
{% block title %}
My account detail
{% endblock %}

{% block content %}
{% load static %}
<div class="container">
    <h1>My account detail</h1>
    <br>
    <div class="row">
        <div class="col-md-6">
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <div class="alert alert-{% if message.tags %}{{ message.tags }}{% endif %} alert-dismissible fade show"
                    role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                {% endfor %}
            </ul>
            {% endif %}
            <p><strong>First name:</strong> {{ user.first_name }}</p>
            <p><strong>Last name:</strong> {{ user.last_name }}</p>
            <p><strong>Email:</strong> {{ user.email }}</p>
            <p><strong>Role:</strong> {{ rol }}</p>
            <br />

            <a href="{% url 'accounts:delete' %}" class="genric-btn danger">Delete account</a>

        </div>
        <div class="col-md-6">
            {% if user.role == 1 %}
            <img src="{% static 'img/profile/reviewer.png' %}" width=30% alt="">
            {% elif user.role == 2 %}
            <img src="{% static 'img/profile/developer.png' %}" width=30% alt="">
            {% elif user.role == 3 %}
            <img src="{% static 'img/profile/provider.png' %}" width=30% alt="">
            {% elif user.role == 4 %}
            <img src="{% static 'img/profile/admin.png' %}" width=30% alt="">
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

templates/accounts/login.html
{% extends "base.html" %}

{% block title %}
Login
{% endblock %}

{% block content %}
<!--================login_part Area =================-->
<section class="login_part">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6 col-md-6">
                <div class="login_part_text text-center">
                    <div class="login_part_text_iner">
                        <h2>New to our site?</h2>
                        <p>There are advances being made in science and technology
                            everyday, and a good example of this is the CRPA. Continue to contribute to our future!</p>
                        <a href="{% url 'accounts:register' %}" class="btn_3">Create an Account</a>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 col-md-6">
                <div class="login_part_form">
                    <div class="login_part_form_iner">
                        <h3>Welcome Back ! <br>
                            Please Sign in now</h3>

                        {% if messages %}
                        <ul class="messages">
                            {% for message in messages %}
                            <div class="alert alert-{% if message.tags %}{{ message.tags }}{% endif %} alert-dismissible fade show"
                                role="alert">
                                {{ message }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            {% endfor %}
                        </ul>
                        {% endif %}
                        <form class="row contact_form" action="#" method="post">
                            <div class="col-md-12 form-group p_star">{% csrf_token %}
                                {% if next_url %}
                                <input type="hidden" name="next" value="{{ next_url }}">
                                {% endif %}
                                <div class="form-control">
                                    {{ form.email }}
                                </div>
                                <div class="form-validation">{{ form.email.errors }}</div>
                            </div>
                            <div class="col-md-12 form-group p_star">
                                <div class="form-control">
                                    {{ form.password }}
                                </div>
                                <div class="form-validation">{{ form.password.errors }}</div>
                            </div>
                            <div class="col-md-12 form-group">
                                <div class="creat_account d-flex align-items-center">
                                    <input type="checkbox" id="f-option" name="selector">
                                    <label for="f-option">Remember me</label>
                                </div>

                                <button type="submit" value="submit" class="btn_3">
                                    log in
                                </button>
                                <a class="lost_pass" href="#">forget password?</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!--================login_part end =================-->

{% endblock %}

templates/accounts/register.html
{% extends "base.html" %}

{% block title %}
Register
{% endblock %}

{% block content %}
<section class="login_part">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6 col-md-6">
                <div class="login_part_form">
                    <div class="login_part_form_iner">
                        <h3>Join us ! Start finding<br>
                            exactly what you want at CRPA</h3>

                        {% if messages %}
                        <ul class="messages">
                            {% for message in messages %}
                            <div class="alert alert-{% if message.tags %}{{ message.tags }}{% endif %} alert-dismissible fade show"
                                role="alert">
                                {{ message }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            {% endfor %}
                        </ul>
                        {% endif %}
                        <form class="row contact_form" method="post">{% csrf_token %}
                            <div class="col-md-12 form-group p_star">
                                {% if next_url %}
                                <input type="hidden" name="next" value="{{ next_url }}">
                                {% endif %}
                                <div class="form-control">
                                    {{ form.first_name }}
                                </div>
                                <div class="form-validation">{{ form.first_name.errors }}</div>
                            </div>
                            <div class="col-md-12 form-group p_star">
                                <div class="form-control">
                                    {{ form.last_name }}
                                </div>
                                <div class="form-validation">{{ form.last_name.errors }}</div>
                            </div>
                            <div class="col-md-12 form-group p_star">
                                <div class="form-control">
                                    {{ form.email }}
                                </div>
                                <div class="form-validation">{{ form.email.errors }}</div>
                            </div>
                            <div class="col-md-12 form-group p_star">
                                <div class="form-control">
                                    {{ form.password }}
                                </div>
                                <div class="form-validation">{{ form.password.errors }}</div>
                            </div>
                            <div class="col-md-12 form-group p_star">
                                <div class="form-control">
                                    <input class="form-control" id="id_password2" name="password2" type="password"
                                        onChange="onChange()" placeholder="Confirm password" required />
                                </div>
                                <div class="form-validation" id="confpassval"></div>
                            </div>
                            <div class="col-md-12 form-group p_star">
                                <div class="form-select" id="default-select">
                                    <select id="id_role" name="role" required>
                                        <option value="" disabled selected>Role</option>
                                        {% for x, y in form.fields.role.choices %}
                                        <option value="{{ x }}" {% if form.fields.role.value == x %}
                                            selected{% endif %}>
                                            {{ y }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                                <div class="form-validation">{{ form.role.errors }}</div>
                            </div>
                            <div class="col-md-12 form-group">
                                <button type="submit" value="submit" id="xvxv" class="btn_3">
                                    Register
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 col-md-6">
                <div class="login_part_text text-center">
                    <div class="login_part_text_iner">
                        <h2>You didn't know about CRPAsite?</h2>
                        <p>Collaborate with our component classification. You'll find the cognitive components you need
                            the fastest way.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        function onChange() {
            const password = document.querySelector('input[name=password]');
            const confirm = document.querySelector('input[name=password2]');
            if (confirm.value === password.value) {
                $("#xvxv").removeAttr("disabled");
                confirm.setCustomValidity('');
                $("#confpassval").html('');
            } else {
                $("#xvxv").attr("disabled", true);
                confirm.setCustomValidity('Passwords do not match');
                $("#confpassval").html('Passwords do not match');
            }
        }
    </script>
</section>
{% endblock %}

templates/accounts/register_reviewer.html
{% extends "base.html" %}

{% block title %}
Register
{% endblock %}

{% block content %}
{% load static %}
{% if request.user.role == 1 %}
<section class="login_part">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6 col-md-6">
                <div class="login_part_form">
                    <div class="login_part_form_iner">
                        <h3>Join us ! Start finding<br>
                            exactly what you want at CRPA</h3>

                        {% if messages %}
                        <ul class="messages">
                            {% for message in messages %}
                            <div class="alert alert-{% if message.tags %}{{ message.tags }}{% endif %} alert-dismissible fade show"
                                role="alert">
                                {{ message }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            {% endfor %}
                        </ul>
                        {% endif %}
                        <form class="row contact_form" method="post">{% csrf_token %}
                            <div class="col-md-12 form-group p_star">
                                {% if next_url %}
                                <input type="hidden" name="next" value="{{ next_url }}">
                                {% endif %}
                                <input type="hidden" id="id_role" name="role" value="2">
                                <div class="form-control">
                                    {{ form.first_name }}
                                </div>
                                <div class="form-validation">{{ form.first_name.errors }}</div>
                            </div>
                            <div class="col-md-12 form-group p_star">
                                <div class="form-control">
                                    {{ form.last_name }}
                                </div>
                                <div class="form-validation">{{ form.last_name.errors }}</div>
                            </div>
                            <div class="col-md-12 form-group p_star">
                                <div class="form-control">
                                    {{ form.email }}
                                </div>
                                <div class="form-validation">{{ form.email.errors }}</div>
                            </div>
                            <div class="col-md-12 form-group p_star">
                                <div class="form-control">
                                    {{ form.password }}
                                </div>
                                <div class="form-validation">{{ form.password.errors }}</div>
                            </div>
                            <div class="col-md-12 form-group p_star">
                                <div class="form-control">
                                    <input class="form-control" id="id_password2" name="password2" type="password"
                                        onChange="onChange()" placeholder="Confirm password" required />
                                </div>
                                <div class="form-validation" id="confpassval"></div>
                            </div>
                            <div class="col-md-12 form-group">
                                <button type="submit" value="submit" id="xvxv" class="btn_3">
                                    Register
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 col-md-6">
                <div class="login_part_text text-center">
                    <div class="login_part_text_iner">
                        <h2>You didn't know about CRPAsite?</h2>
                        <p>Collaborate with our component classification. You'll find the cognitive components you need
                            the fastest way.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        function onChange() {
            const password = document.querySelector('input[name=password]');
            const confirm = document.querySelector('input[name=password2]');
            if (confirm.value === password.value) {
                $("#xvxv").removeAttr("disabled");
                confirm.setCustomValidity('');
                $("#confpassval").html('');
            } else {
                $("#xvxv").attr("disabled", true);
                confirm.setCustomValidity('Passwords do not match');
                $("#confpassval").html('Passwords do not match');
            }
        }
    </script>
</section>
{% else %}
<div class="slider-area ">
    <!-- Mobile Menu -->
    <div class="single-slider slider-height2 d-flex align-items-center"
        data-background="{% static 'img/error_phone.jpg' %}">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="hero-cap text-center">
                        <h2>Ups!</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- slider Area End-->

<!-- product list part start-->
<section class="about_us padding_top">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-8">
                <div class="about_us_content">
                    <h5>An error has occurred</h5>
                    <h3>Check that your account allows you to access what you want, and if you have problems contact the
                        customer service of our platform <a href="mailto:support@crpa.site">support@crpa.site</a></h3>
                </div>
            </div>
        </div>
    </div>
</section>
{% endif %}

{% endblock %}