carts/urls.py
from django.urls import path
from .views import (
    cart_home,
    cart_update,
    checkout_home,
    checkout_done_view,
    cart_detail_api_view,
)

app_name = "carts"

urlpatterns = [
    path("", cart_home, name="home"),
    path("api/", cart_detail_api_view, name="home_api"),
    path("checkout/", checkout_home, name="checkout"),
    path("update/", cart_update, name="update"),
    path("success/<str:order_code>/<int:products>/", checkout_done_view, name="success"),
]

crpasite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import home_page, termandconds_page
from taxcategs.views import taxonomy_view


urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("", home_page, name="home_url"),
        path("termandconds", termandconds_page, name="termandconds_url"),
        path("accounts/", include("accounts.urls")),
        path("products/", include("products.urls"), name="products"),
        path("addresses/", include("addresses.urls")),
        path("cart/", include("carts.urls")),
        path("search/", include("search.urls")),
        path("categories/", include("taxcategs.urls")),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

products/urls.py
from django.urls import path, include, re_path
from .views import ProductListView, ProductDetailView, CreateProductView, MyProductListView, LatestProductListView, export_products
import private_storage.urls

app_name = "products"

urlpatterns = [
    path("", ProductListView.as_view(), name="list"),
    path("latest/", LatestProductListView.as_view(), name="latest"),
    path("purchased/", MyProductListView.as_view(), name="my_list"),
    path("new/", CreateProductView.as_view(), name="create"),
    path("detail/<slug:slug>/", ProductDetailView.as_view(), name="detail"),
    path('export/', export_products, name='export_products'),
    # path('private-data/<str:code>/<int:year>/<str:subdir>/<uuid:pk>/<str:filename>', ProductDownloadView.as_view(), name="file_download"),
    # path('private-data/<str:filename>', ProductDownloadView.as_view(), name="file_download"),
    re_path('^private-data/', include(private_storage.urls)),
]

taxcategs/urls.py
from django.urls import path, re_path
from .views import CategoriesListView, CategoryDetailView, AddInputFormatSupportedView, AddKnowledgeSourceView, AddCommentView, AddCategoryTermProposalView, select_proposal_view, ProposalListView, review_multiple_form, CategoriesListReview, TaxCategoryDetailView, taxonomy_view, ProductNavigateCategoryView, CommentListView, export_taxonomy, CommentDetailView, CategTermsListView
from django.contrib.auth.views import LogoutView

app_name = "taxcategs"

urlpatterns = [
    path('listview/', CategoriesListView.as_view(), name="ul_taxonomy"),
    path('navigate/', taxonomy_view, name="categoryterm_list"),
    path('navigate/<int:pk>/', ProductNavigateCategoryView.as_view(), name="product_categoryterm_list"),
    path('view/<int:pk>/', CategoryDetailView.as_view(), name="categoryterm_detail"),
    path('detail/<int:pk>/', TaxCategoryDetailView.as_view(), name="taxcategory_detail"),
    path('review/<int:id>/', review_multiple_form, name="review"),
    path('terms/<int:pk>/', CategTermsListView.as_view(), name="terms"),
]

urlpatterns += [   
    path('select/', select_proposal_view, name='categoryterm_create'),
    path('proposal/', AddCategoryTermProposalView.as_view(), name='categoryterm_proposal'),
    re_path(r'^myproposals/(?:(?P<status>\d)/)?$', ProposalListView.as_view(), name='categoryterm_myproposal'),
    path('input/', AddInputFormatSupportedView.as_view(), name='inputformatsupported_create'),
    path('knowledgesource/', AddKnowledgeSourceView.as_view(), name='knowledgesource_create'),
    re_path(r'^comment/(?:(?P<categterm>\d)/)?$', AddCommentView.as_view(), name='comment_create'),
    path('comment_detail/<int:pk>/', CommentDetailView.as_view(), name="comment_detail"),
    re_path(r'^comment/list/(?:(?P<mine>\d||<pk>\d)/)?$', CommentListView.as_view(), name='comment_list'),
    path('export/', export_taxonomy, name='export'),
    re_path(r'^reviewproposals/(?:(?P<status>\d)/)?$', CategoriesListReview.as_view(), name='categoryterm_proposalreview'),
]

taxcategs/models.py
from django.db import models
from accounts.models import User as UserModel
from categories.models import CategoryBase
from enum import Enum
from django.core.exceptions import ValidationError
from django.contrib.postgres.fields import ArrayField
from django.urls import reverse
import os
import random

# Create your models here.
class TaxCateg(CategoryBase):
    """
    The category term that stands as the representative of the others.
    """

    name = models.CharField(max_length=50, unique=True)

    class Meta:
        verbose_name = "Taxonomic category"
        verbose_name_plural = "Taxonomic categories"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("taxcategs:taxcategory_detail", kwargs={"pk": self.pk})
    
    def clean(self):
        categ_terms = CategoryTerm.objects.filter(
            tax_categ=self, is_tax_categ=True, active=True
        )
        if len(categ_terms) != 1:
            raise ValidationError(
                "A taxonomic category always has to have at least one associated category term"
            )
        if not (categ_terms[0].term == self.name):
            raise ValidationError(
                "A taxonomic category must always have the same name as its category term"
            )


class KnowledgeSource(models.Model):
    """
    Knowledge source where the information that users relies on when writing a proposal, comes from.
    """

    name = models.CharField(max_length=50)
    url = models.URLField(max_length=200, blank=True)
    creator = models.ForeignKey(
        UserModel, verbose_name="Creator", on_delete=models.CASCADE
    )
    created_at = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)

    class Meta:
        verbose_name = "Knowledge Source"
        verbose_name_plural = "Knowledge Sources"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("taxcategs:categoryterm_create")


class InputFormatSupported(CategoryBase):
    """
    Input format supported by RPA components that are included in a category.
    """

    name = models.CharField(max_length=50, unique=True)

    class Meta:
        verbose_name = "Input Format Supported"
        verbose_name_plural = "Input Formats Supported"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("taxcategs:categoryterm_create")  # , kwargs={"pk": self.pk})

DECISION_CHOICES = (
        ("1", "Accepted"),
        ("2", "Refused"),
        ("3", "Accepted with changes"),
    )

def get_filename_ext(filepath):
    base_name = os.path.basename(filepath)
    name, ext = os.path.splitext(base_name)
    return name, ext

def upload_image_path(instance, filename):
    name, ext = get_filename_ext(filename)
    new_filename = random.randint(1, 123123123123)
    final_name = f"{new_filename}{ext}"
    return f"categories/{final_name}"

class CategoryTerm(models.Model):
    """
    Equivalent categories associated with the same taxonomic category. 
    """

    term = models.CharField(max_length=50)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    is_tax_categ = models.BooleanField(default=False)
    substitute_tax_categ = models.BooleanField(default=False)
    active = models.BooleanField(default=False)
    tax_categ = models.ForeignKey(
        TaxCateg, on_delete=models.CASCADE, blank=True, null=True, limit_choices_to={'active': True},
    )
    knowledge_source = models.ForeignKey(KnowledgeSource, on_delete=models.CASCADE)
    formats_supported = models.ManyToManyField(InputFormatSupported, blank=True)
    user = models.ForeignKey(
        UserModel, verbose_name="Creator", on_delete=models.CASCADE
    )
    categoryChars = ArrayField(models.CharField(max_length=200))
    decision = models.CharField(max_length=5, choices=DECISION_CHOICES, blank=True)
    image = models.ImageField(upload_to=upload_image_path, blank=True)

    class Meta:
        verbose_name = "Category Term"
        verbose_name_plural = "Category Terms"

    @property
    def image_url(self):
        """
        Return self.photo.url if self.image is not None, 
        'url' exist and has a value, else, return None.
        """
        if self.image:
            return getattr(self.image, 'url', None)
        return None

    def create(self, validated_data):
        CategoryTerm.term_unique(self, validated_data.get("term"))
        if not self.request.user.is_authenticated:
            raise ValidationError("User must be authenticated.")
        validated_data.update({"user": self.request.user})
        items = validated_data.pop("formats_supported", None)
        action = CategoryTerm.objects.create(**validated_data)
        if items is not None:
            # items = [InputFormatSupported.objects.create(**item) for item in items]
            # '*' is the "splat" operator: It takes a list as input, and expands it into actual positional arguments in the function call.
            action.formats_supported.add(*items)
        return action

    def term_unique(self, term):
        if CategoryTerm.objects.filter(term=term).exists():
            raise ValidationError('The term of the category term already exists')

    def __str__(self):
        return self.term

    def get_absolute_url(self):
        return reverse("taxcategs:categoryterm_detail", args=[self.pk])

    def clean(self):
        if(self.is_tax_categ and (not self.active)):
             raise ValidationError(
                "For a category to be taxonomical, it always has to be active"
            )
        if len(self.categoryChars) < 1:
            raise ValidationError(
                "A category term cannot have less than one category characteristic"
            )


# If you are using Django >= 1.9 with Postgres you can make use of ArrayField advantages

# A field for storing lists of data. Most field types can be used, you simply pass
# another field instance as the base_field. You may also specify a size. ArrayField
# can be nested to store multi-dimensional arrays.

# https://stackoverflow.com/questions/1110153/what-is-the-most-efficient-way-to-store-a-list-in-the-django-models


# class CategoryChar(models.Model):
#     """
#     Characteristics of a component belonging to one of the taxonomic categories.
#     """
#     rule = models.TextField()
#     active = models.BooleanField(default=False) #¿?
#     category_term = models.ForeignKey(CategoryTerm, verbose_name="Category Term", on_delete=models.CASCADE)
#     creator = models.ForeignKey(UserModel, verbose_name="Creator", on_delete=models.CASCADE)

#     class Meta:
#         verbose_name = "Category characteristic"
#         verbose_name_plural = "Category characteristics"

#     def __str__(self):
#         return self.name


RESULT_CHOICES = (
        ("1", "New category term"),
        ("2", "Taxonomic category proposal save as new category term"),
        ("3", "New taxonomic category"),
        ("4", "Taxonomic category replaced"),
    )

class Report(models.Model):
    """
    Report of the decision taken after reviewing the proposal.
    """
    result = models.CharField(max_length=5, choices=RESULT_CHOICES, blank=True)
    categ_term = models.ForeignKey(
        CategoryTerm, verbose_name="Proposal reviewed", on_delete=models.CASCADE
    )
    explanation = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    review_user = models.ForeignKey(
        UserModel, verbose_name="Reviewer", on_delete=models.CASCADE
    )

    class Meta:
        verbose_name = "Decision"
        verbose_name_plural = "Decisions"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("taxcategs:categoryterm_create")

class Comment(models.Model):
    user = models.ForeignKey(UserModel, verbose_name="Author", on_delete=models.CASCADE)
    category_term = models.ForeignKey(CategoryTerm, on_delete=models.CASCADE, limit_choices_to={'active': True})
    title = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)
    text = models.TextField()

    class Meta:
        verbose_name = "Comment"
        verbose_name_plural = "Comments"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("taxcategs:comment_list")

templates/categories/animated-taxonomy.html
{% extends 'categories/base.html' %}
{% block title %}
Taxonomy of Cognitive RPA components
{% endblock %}

{% block content %}
{% load static %}
{% load category_tags %}
<div class="container">
  <div class="row">
    <div class="col-md-11">
      <h1>Taxonomy of Cognitive RPA components</h1>
    </div>
    <div class="col-md-1">
      <div class="button-group-area">
        <a href="{% url 'taxcategs:export' %}"
          class="genric-btn primary-border">Download</a>
        {% comment %} <a href="{% url 'products:export_products' %}"
          class="genric-btn primary-border">Components</a> {% endcomment %}
      </div>
    </div>
  </div>
  <div class="row">
  <div class="col-md-2">
  <!-- TODO -->
    <img src="{% static "img/leyenda.png" %}" alt="help" width="360em" style="padding: 3em;">
  </div>
    <div class="col-md-10">
      {% if not taxcateg_hierarchy %}
      <br>
      <h2 style="color:red;">No taxonomy available</h2>
      {% endif %}
      <center>
        <div id="d3Hierarchy"></div>
      </center>
    </div>
  </div>
</div>
{% endblock %}
{% block bottom %}
<script src="{% static 'js/d3.min.js' %}"></script>
<script src="{% static 'js/taxonomy.js' %}"></script>
<script>
{% if taxcateg_hierarchy %}
var taxonomy_data = {{ taxcateg_hierarchy|safe }}
taxonomytree(taxonomy_data);
{% endif %}
$(document).ready(function(){
  $('[data-toggle="tooltip"]').tooltip();   
});
</script>
{% endblock bottom %}

templates/categories/create-report.html
{% extends 'base.html' %}
{% block title %}
New report
{% endblock %}

{% block content %}
{% load static %}
<div class="container">
    <h3 class="mb-30">New report</h3>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <div class="alert alert-{% if message.tags %}{{ message.tags }}{% endif %} alert-dismissible fade show"
            role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endfor %}
    </ul>
    {% endif %}
    {% if reptaxcateg and not taxonomicategory.active %}
    <ul class="messages">
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            This proposal is intended to be a <strong>new</strong> taxonomic category:
            <strong>{{taxonomicategory}}</strong>.
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">×</span>
            </button>
        </div>
    </ul>
    {% elif reptaxcateg and taxonomicategory.active %}
    <ul class="messages">
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            This proposal is intended to replace the taxonomic category <strong>{{taxonomicategory}}</strong>.
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">×</span>
            </button>
        </div>
    </ul>
    {% endif %}

    <form method="POST">{% csrf_token %}
        <div class="row">
            <div class="col-md-12">
                <p>
                    {{ category_term_form.term.label_tag }}
                    {{ category_term_form.term }}
                    <div class="form-validation">{{ category_term_form.term.errors }}</div>
                </p>
            </div>
            <div class="col-md-12">
                <p>
                    {{ category_term_form.description.label_tag }}
                    {{ category_term_form.description }}
                    <div class="form-validation">{{ category_term_form.description.errors }}</div>
                </p>
            </div>
            <div class="col-md-12">
                <p>
                    {% if taxonomicategory.active %}
                    <label>Taxonomic category</label>
                    {% else %}
                    <label>New taxonomic category proposal</label>
                    {% endif %}
                    <div class="single-input">{{ taxonomicategory }}</div>
                </p>
            </div>
            {% if not taxonomicategory.active %}
            <div class="col-md-12">
                <br/><br/><p>
                    <label>Parent category</label>
                    <div class="single-input">{{ taxonomicategory.parent }}</div>
                </p>
            </div>
            {% endif %}
            <div class="col-md-12">
                <p>
                    <div>{{ category_term_form.knowledge_source.label_tag }}</div>
                    {{ category_term_form.knowledge_source }}
                    <div class="form-validation">{{ category_term_form.knowledge_source.errors }}</div>
                </p>
            </div>
            <div class="col-md-12">
                <p>
                    {{ category_term_form.formats_supported.label_tag }}
                    {{ category_term_form.formats_supported }}
                    <div class="form-validation">{{ category_term_form.formats_supported.errors }}</div>
                </p>
            </div>
            <div class="col-md-12">
                <p>
                    {{ category_term_form.categoryChars.label_tag }}
                    {{ category_term_form.categoryChars }}
                    <div class="form-validation">{{ category_term_form.categoryChars.errors }}</div>
                </p>
            </div>
            <div class="col-md-12">
                <h3>Category term report</h3><br>
            </div>
            <div class="col-md-12">
                <p>
                    <div>{{ category_term_form.decision.label_tag }}</div>
                    {{ category_term_form.decision }}
                    <div class="form-validation">{{ category_term_form.decision.errors }}</div>
                </p>
            </div>

            <div class="col-md-12 cat_result">
                <p>
                    <div>{{ report_form.result.label_tag }}</div>
                    <select name="result" id="id_result" style="display: none;">
                        {% for x, y in report_form.fields.result.choices %}
                        {% if reptaxcateg and x > "2" %}
                        {% if not taxonomicategory.active %}
                        {% if x == "3" %}
                        <option value="{{ x }}" {% if report_form.fields.result.value == x %} selected{% endif %}>
                            {{ y }}
                        </option>
                        {% endif %}
                        {% else %}
                        <option value="{{ x }}" {% if report_form.fields.result.value == x %} selected{% endif %}>
                            {{ y }}
                        </option>
                        {% endif %}

                        {% elif not reptaxcateg and x < "3" %}
                        <option value="{{ x }}" {% if report_form.fields.result.value == x %} selected{% endif %}>
                            {{ y }}
                        </option>
                        {% endif %}
                        {% endfor %}
                    </select>
                    <div class="form-validation">{{ report_form.result.errors }}</div>
                </p>
            </div>

            <div class="col-md-12">
                <p>
                    <div>{{ report_form.explanation.label_tag }}</div>
                    {{ report_form.explanation }}
                    <div class="form-validation">{{ report_form.explanation.errors }}</div>
                </p>
            </div>
            <div class="sup11"></div>

            <div class="col-md-12">
                <button type="submit" value="submit" class="btn_3">
                    Save
                </button>
            </div>
        </div>
    </form>
</div>

<script src="{% static 'js/vendor/jquery-1.12.4.min.js' %}"></script>
<script>
    $(document).ready(function () {
        var decision = $('.cat_decision'); // input field decision
        var result = $('.cat_result'); //Input field result
        a = decision.val() == "1";
        b = decision.val() == "3";
        if (a || b) {
            $(".sup12").remove();
            result.show();
        } else {
            result.hide();
            $(".sup11").after("<input class='sup12' type='hidden' name='result' id='id_result'>");
        }
        $(decision).focus(function () {
            a = decision.val() == "1";
            b = decision.val() == "3";
            if (a || b) {
                $(".sup12").remove();
                result.show();
            } else {
                result.hide();
                $(".sup11").after("<input class='sup12' type='hidden' name='result' id='id_result'>");
            }
        });
    });
</script>
{% endblock %}

templates/categories/create.html
{% extends 'base.html' %}
{% block title %}
Create a category term proposal
{% endblock %}

{% block content %}
<div class="container">
    <h3>Register a category term proposal</h3>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <div class="alert alert-{% if message.tags %}{{ message.tags }}{% endif %} alert-dismissible fade show"
            role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endfor %}
    </ul>
    {% endif %}

    {% if request.taxcategdecision == 1 %}
    <ul class="messages">
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            {{reptaxcateg}}
            This proposal is intended to replace the taxonomic category {{taxonomicategory}}.
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">×</span>
            </button>
        </div>
    </ul>
    {% elif request.taxcategdecision == 2 %}
    <ul class="messages">
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            This proposal is intended to be a new taxonomic category.
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">×</span>
            </button>
        </div>
    </ul>
    {% endif %}
    <form method="POST" enctype="multipart/form-data" >{% csrf_token %}
        <p>
            {{ form.term.label_tag }}
            {{ form.term }}
            <div class="form-validation">{{ form.term.errors }}</div>
        </p>
        <p>
            {{ form.description.label_tag }}
            {{ form.description }}
            <div class="form-validation">{{ form.description.errors }}</div>
        </p>
        <p>
            {{ form.tax_categ.label_tag }}
            <select name="result" id="id_result" style="display: none;">
                {% for category in level_zero %}
                <option value="{{ category.pk }}" {% if form.fields.tax_categ.value == category.pk %}
                    selected{% endif %}>{{ category }}</option>
                {% include 'categories/snippets/taxcateg-child-form.html' with c=category sufix=">" val=form.fields.tax_categ.value %}
                {% endfor %}
            </select>
            <div class="form-validation">{{ form.tax_categ.errors }}</div>
        </p>
        <p>
            {{ form.knowledge_source.label_tag }}
            {{ form.knowledge_source }}
            <div class="form-validation">{{ form.knowledge_source.errors }}</div>
        </p>
        <p>
            {{ form.image.label_tag }}
            {{ form.image }}
            <div class="form-validation">{{ form.image.errors }}</div>
        </p>
        <p>
            {{ form.formats_supported.label_tag }}
            {{ form.formats_supported }}
            <div class="form-validation">{{ form.formats_supported.errors }}</div>
        </p>
        <p>
            {{ form.categoryChars.label_tag }}
            {{ form.categoryChars }}
            <div class="form-validation">{{ form.categoryChars.errors }}</div>
        </p>
        <button type="submit" value="submit" class="btn_3">
            Save
        </button>
    </form>
</div>
{% endblock %}

templates/categories/list.html
{% extends 'base.html' %}
{% block title %}
{{status}}
{% endblock %}

{% block content %}


<div class="container">
    {% if request.user.role == 1 or 4 %}
    <div class="row">
        <div class="col-md-7">
            <h1>{{status}}</h1>
        </div>
        <div class="col-md-5">
            <div class="button-group-area mt-10">
                <a href="{% url 'taxcategs:categoryterm_proposalreview' %}?status=3"
                    class="genric-btn primary-border">Pending</a>
                <a href="{% url 'taxcategs:categoryterm_proposalreview' %}?status=2"
                    class="genric-btn success-border">Rejected</a>
                <a href="{% url 'taxcategs:categoryterm_proposalreview' %}?status=1"
                    class="genric-btn info-border">Accepted</a>
            </div>
        </div>
    </div>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <div class="alert alert-{% if message.tags %}{{ message.tags }}{% endif %} alert-dismissible fade show"
            role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endfor %}
    </ul>
    {% endif %}
    <div class="section-top-border">
        <h3>Category Terms</h3>
        <div class="progress-table-wrap">
            <div class="progress-table">
                {% if object_list %}
                <div class="table-head">
                    {% if not status or status == "Proposals for review" %}
                    <div class="categoryterm_1">Review Term</div>
                    {% else %}
                    <div class="categoryterm_1">Term</div>
                    {% endif %}
                    <div class="categoryterm_">Taxonomic Category</div>
                    <div class="categoryterm_">Knowledge Source</div>
                    <div class="categoryterm_">Created At</div>
                    <div class="categoryterm_n">Replacement?</div>
                </div>
                {% for c in object_list %}
                <div class="table-row">
                    {% if not status or status == "Proposals for review" %}
                    <div class="categoryterm_1"><a href="/categories/review/{{ c.pk }}/">{{ c.term }}</a></div>
                    {% else %}
                    <div class="categoryterm_1"><a href="/categories/view/{{ c.pk }}/">{{ c.term }}</a></div>
                    {% endif %}
                    <div class="categoryterm_">{{ c.tax_categ }}</div>
                    <div class="categoryterm_">{{ c.knowledge_source }}</div>
                    <div class="categoryterm_">{{ c.created_at }}</div>
                    {% if not status or status == "Proposals for review" %}
                    <div class="categoryterm_n"><a href="/categories/view/{{ c.pk }}/">{{ c.substitute_tax_categ }}</a>
                    </div>
                    {% else %}
                    <div class="categoryterm_n">{{ c.substitute_tax_categ }}</div>
                    {% endif %}
                </div>
                {% endfor %}
                {% else %}
                <p>No categories yet.</p>
                {% endif %}
            </div>
        </div>
    </div>

    <nav class="blog-pagination justify-content-center d-flex">
        <ul class="pagination">
            {% if page_obj.has_previous %}
            <li class="page-item">
                <a href="?page=1&status={{ statusnumber }}" class="page-link">
                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-chevron-double-left"
                        fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd"
                            d="M8.354 1.646a.5.5 0 0 1 0 .708L2.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0z" />
                        <path fill-rule="evenodd"
                            d="M12.354 1.646a.5.5 0 0 1 0 .708L6.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0z" />
                    </svg>
                </a>
            </li>
            <li class="page-item">
                <a href="?page={{ page_obj.previous_page_number }}&status={{ statusnumber }}" class="page-link"
                    aria-label="Previous">
                    <i class="ti-angle-left"></i></a>
            </li>
            {% endif %}
            {% for i in page_obj.paginator.page_range %}
            {% if page_obj.number == i %}
            <li class="page-item activo"><a href="#" class="page-link">{{ i }}</a></li>
            {% else %}
            <li class="page-item"><a href="?page={{ i }}&status={{ statusnumber }}" class="page-link">{{ i }}</a></li>
            {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
            <li class="page-item">
                <a href="?page={{ page_obj.next_page_number }}&status={{ statusnumber }}" class="page-link"
                    aria-label="Next">
                    <i class="ti-angle-right"></i>
                </a>
            </li>
            <li class="page-item">
                <a href="?page={{ page_obj.paginator.num_pages }}&status={{ statusnumber }}" class="page-link"
                    aria-label="Last">
                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-chevron-double-right"
                        fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd"
                            d="M3.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L9.293 8 3.646 2.354a.5.5 0 0 1 0-.708z" />
                        <path fill-rule="evenodd"
                            d="M7.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L13.293 8 7.646 2.354a.5.5 0 0 1 0-.708z" />
                    </svg>
                </a>
            </li>
            {% endif %}
        </ul>
    </nav>



    {% else %}
    <h2 class="form-validation">Reviewer must be authenticated</h2>
    {% endif %}
    {{qqq}}
</div>
{% endblock %}