accounts/urls.py
from django.urls import path
from .views import login_page, register_page, guest_register_view, register_page_reviewer, AccountDetailView, destroy
from django.contrib.auth.views import LogoutView

app_name = "accounts"

urlpatterns = [
    path("login/", login_page, name="login"),
    path("register/", register_page, name="register"),
    path("view/", AccountDetailView.as_view(), name="view"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("guest/register/", guest_register_view, name="guest_register"),
    path("reviewer/register/", register_page_reviewer, name="reviewer_register"),
    path("delete/", destroy, name="delete"),
]

addresses/urls.py
from django.urls import path
from .views import checkout_address_create_view, checkout_address_reuse_view

app_name = "addresses"

urlpatterns = [
    path(
        "checkout-create-view",
        checkout_address_create_view,
        name="checkout_create_view",
    ),
    path(
        "checkout-reuse-view", checkout_address_reuse_view, name="checkout_reuse_view"
    ),
]

carts/urls.py
from django.urls import path
from .views import (
    cart_home,
    cart_update,
    checkout_home,
    checkout_done_view,
    cart_detail_api_view,
)

app_name = "carts"

urlpatterns = [
    path("", cart_home, name="home"),
    path("api/", cart_detail_api_view, name="home_api"),
    path("checkout/", checkout_home, name="checkout"),
    path("update/", cart_update, name="update"),
    path("success/<str:order_code>/<int:products>/", checkout_done_view, name="success"),
]

crpasite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import home_page, termandconds_page
from taxcategs.views import taxonomy_view


urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("", home_page, name="home_url"),
        path("termandconds", termandconds_page, name="termandconds_url"),
        path("accounts/", include("accounts.urls")),
        path("products/", include("products.urls"), name="products"),
        path("addresses/", include("addresses.urls")),
        path("cart/", include("carts.urls")),
        path("search/", include("search.urls")),
        path("categories/", include("taxcategs.urls")),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

products/urls.py
from django.urls import path, include, re_path
from .views import ProductListView, ProductDetailView, CreateProductView, MyProductListView, LatestProductListView, export_products
import private_storage.urls

app_name = "products"

urlpatterns = [
    path("", ProductListView.as_view(), name="list"),
    path("latest/", LatestProductListView.as_view(), name="latest"),
    path("purchased/", MyProductListView.as_view(), name="my_list"),
    path("new/", CreateProductView.as_view(), name="create"),
    path("detail/<slug:slug>/", ProductDetailView.as_view(), name="detail"),
    path('export/', export_products, name='export_products'),
    # path('private-data/<str:code>/<int:year>/<str:subdir>/<uuid:pk>/<str:filename>', ProductDownloadView.as_view(), name="file_download"),
    # path('private-data/<str:filename>', ProductDownloadView.as_view(), name="file_download"),
    re_path('^private-data/', include(private_storage.urls)),
]

carts/models.py
from django.conf import settings
from django.db import models
from products.models import Product
from django.db.models.signals import pre_save, m2m_changed
from decimal import Decimal

User = settings.AUTH_USER_MODEL


class CartManager(models.Manager):
    def new_or_get(self, request):
        cart_id = request.session.get("cart_id", None)
        qs = self.get_queryset().filter(id=cart_id)
        if qs.count() == 1:
            new_obj = False
            cart_obj = qs.first()
            if request.user.is_authenticated and cart_obj.user is None:
                cart_obj.user = request.user
                cart_obj.save()
        else:
            cart_obj = self.new(user=request.user)
            new_obj = True
            request.session["cart_id"] = cart_obj.id
        return cart_obj, new_obj

    def new(self, user=None):
        user_obj = None
        if user is not None:
            if user.is_authenticated:
                user_obj = user
        return self.model.objects.create(user=user_obj)


class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    products = models.ManyToManyField(Product, blank=True)
    subtotal = models.DecimalField(max_digits=30, decimal_places=4, default=0)
    total = models.DecimalField(max_digits=30, decimal_places=4, default=0)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    objects = CartManager()

    def __str__(self):
        return str(self.id)


def m2m_changed_cart_receiver(sender, instance, action, *args, **kwargs):
    if action == "post_add" or action == "post_remove" or action == "post_clear":
        products = instance.products.all()
        total = 0
        for x in products:
            total += x.price
        if instance.subtotal != total:
            instance.subtotal = total
            instance.save()


m2m_changed.connect(m2m_changed_cart_receiver, sender=Cart.products.through)


def pre_save_cart_receiver(sender, instance, *args, **kwargs):
    if instance.subtotal > 0:
        instance.total = Decimal(instance.subtotal) * Decimal(1.08)
    else:
        instance.total = 0


pre_save.connect(pre_save_cart_receiver, sender=Cart)

carts/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from products.models import Product, ProductsAvailable
from .models import Cart
from orders.models import Order
from accounts.forms import LoginForm, GuestForm
from billing.models import BillingProfile
from addresses.forms import AddressForm
from addresses.models import Address
from decimal import Decimal
from django.http import HttpResponseRedirect
from django.contrib import messages


def cart_detail_api_view(request):
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    products = [
        {
            "id": x.id,
            "url": x.get_absolute_url(),
            "title": x.title,
            "price": format(x.price, ".2f"),
        }
        for x in cart_obj.products.all()
    ]
    cart_data = {
        "products": products,
        "subTotal": format(cart_obj.subtotal, ".2f"),
        "total": format(cart_obj.total, ".2f"),
    }
    return JsonResponse(cart_data, status=200)


def cart_home(request):
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    return render(request, "carts/home.html", {"cart": cart_obj})


def cart_update(request):
    product_id = request.POST.get("product_id")
    if product_id is not None:

        # get product or return cart page
        try:
            product_obj = Product.objects.get(id=product_id)
        except Product.DoesNotExist:
            # ajax error response
            if request.is_ajax():
                json_data = {
                    "added": False,
                    "removed": False,
                }
                return JsonResponse(json_data, status=409)

            return redirect("carts:home")

        cart_obj, new_obj = Cart.objects.new_or_get(request)

        if product_obj in cart_obj.products.all():
            # remove product cart
            cart_obj.products.remove(product_obj)
            product_added = False
        else:
            # add product cart
            cart_obj.products.add(product_obj)
            product_added = True

        # cart product count update
        request.session["cart_items"] = cart_obj.products.count()

        if request.is_ajax():
            json_data = {
                "added": product_added,
                "removed": not product_added,
                "cartItemCount": cart_obj.products.count(),
            }
            return JsonResponse(json_data, status=200)

    # no product_id in post request
    return redirect("carts:home")


def checkout_home(request):
    cart_obj, cart_created = Cart.objects.new_or_get(request)
    order_obj = None
    billing_address_id = request.session.get("billing_address_id", None)
    shipping_address_id = request.session.get("shipping_address_id", None)

    if cart_created or cart_obj.products.count() == 0:
        return redirect("carts:home")

    billing_profile, billing_profile_created = BillingProfile.objects.new_or_get(
        request
    )
    address_qs = None
    if billing_profile is not None:
        if request.user.is_authenticated:
            address_qs = Address.objects.filter(billing_profile=billing_profile).all().distinct("address_line_1", "postal_code")
        order_obj, order_obj_created = Order.objects.new_or_get(
            billing_profile, cart_obj
        )

        if shipping_address_id:
            order_obj.shipping_address = Address.objects.get(id=shipping_address_id)
            del request.session["shipping_address_id"]
        if billing_address_id:
            order_obj.billing_address = Address.objects.get(id=billing_address_id)
            del request.session["billing_address_id"]
        if billing_address_id or shipping_address_id:
            order_obj.save()

    if request.method == "POST":
        "some check that order is done"
        is_done = order_obj.check_done()
        if request.user.is_authenticated:
            user = request.user
        for produuuuuct in cart_obj.products.all():
            if produuuuuct.user.pk == user.pk:
                messages.warning(request, "Cannot buy one of your products")
                return render(request, "carts/home.html", {})
        if is_done:
            order_obj.mark_paid()
            # Add product to available list
            if ProductsAvailable.objects.filter(user=user).exists():
                p = ProductsAvailable.objects.get(user=user)
                p.products.add(*cart_obj.products.all())
            else:
                p = ProductsAvailable.objects.create(user=user)
                p.products.add(*cart_obj.products.all())
            del request.session["cart_id"] 
            return HttpResponseRedirect(reverse("carts:success", kwargs={"order_code": order_obj.order_code, "products": p.pk}))

    context = {
        "object": order_obj,
        "billing_profile": billing_profile,
        "login_form": LoginForm(),
        "guest_form": GuestForm(),
        "address_form": AddressForm(),
        "address_qs": address_qs,
    }

    return render(request, "carts/checkout.html", context)


def checkout_done_view(request, **kwargs):
    prods = ProductsAvailable.objects.get(pk=kwargs["products"])
    context = {"order_code": kwargs["order_code"], "products": prods.products.all()}
    return render(request, "carts/checkout-done.html", context)

templates/carts/checkout-done.html
{% extends "base.html" %}
{% load l10n %}

{% block title %}
Checkout Done
{% endblock %}

{% block content %}
<div class="container">
    <div class="col-6 mx-auto py-5 text-center">
        <h1 class="display-1"> Thank you for your order.</h1>
        <p><b>Order Code: </b> {{ order_code }}</p>
        <p><strong>Available to download:</strong></p>
        {% for product in products %}
        <p><a href="/products/private-data/{{product.component}}">{{product}}</a></p>
        {% endfor %}
        <a class="btn btn-info" href="{% url 'home_url' %}"> Return Home</a>
    </div>
</div>
{% endblock %}

templates/carts/checkout.html
{% extends "base.html" %}
{% load l10n %}

{% block title %}
Checkout
{% endblock %}

{% block content %}
<div class="container">
    {% if object.order_code %}
    {{ object.order_code }} -- {{ object.cart.id }}
    {% endif %}
    <br>
    {% if not billing_profile %}

    {% comment %} <div class="row"> {% endcomment %}
        <div style="width: 50%; margin: 0 auto;">
            <p class="lead text-center"><b>Login</b></p>
            <div class="row d-flex justify-content-center">
                <div class="col-md-12">
                    {% include "accounts/snippets/login_form.html" with form=login_form next_url=request.build_absolute_uri %}
                </div>
            </div>
        </div>
        {% comment %} <div class="col-md-6 text-center">
            <b>Continue as Guest</b>
            <div class="row d-flex justify-content-center">
                <div class="col-md-12">
                    {% url 'accounts:guest_register' as guest_register_url %}
                    {% include "accounts/snippets/login_form.html" with form=guest_form next_url=request.build_absolute_uri action_url=guest_register_url %}
                </div>
            </div>
        </div>
    </div> {% endcomment %}
    {% else %}

    {% if not object.shipping_address %}
    <div class="row d-flex justify-content-center">
        <div class="col-md-12 pt-5">
            <p class="lead">Shipping Address</p>
            <hr>
        </div>
        <div class="col-md-6">
            {% url 'addresses:checkout_create_view' as checkout_create_view %}
            {% include "addresses/snippets/form.html" with form=address_form next_url=request.build_absolute_uri action_url=checkout_create_view address_type='shipping' %}
        </div>
        <div class="col-md-6">
            {% url 'addresses:checkout_reuse_view' as checkout_reuse_view %}
            {% include 'addresses/snippets/prev_addresses.html' with addresses_qs=address_qs next_url=request.build_absolute_uri address_type='shipping' action_url=checkout_reuse_view %}
        </div>
    </div>
    {% elif not object.billing_address %}
    <div class="row d-flex justify-content-center">
        <div class="col-md-12 pt-5">
            <p class="lead">Billing Address</p>
            <hr>
        </div>
        <div class="col-md-6">
            {% url 'addresses:checkout_create_view' as checkout_create_view %}
            {% include "addresses/snippets/form.html" with form=address_form next_url=request.build_absolute_uri action_url=checkout_create_view address_type='billing' %}
        </div>
        <div class="col-md-6">
            {% url 'addresses:checkout_reuse_view' as checkout_reuse_view %}
            {% include 'addresses/snippets/prev_addresses.html' with addresses_qs=address_qs next_url=request.build_absolute_uri address_type='billing' action_url=checkout_reuse_view %}
        </div>
    </div>
    {% else %}
    <h1>Checkout</h1>
    <p>Cart Items:
        {% for prodcut in object.cart.products.all %}
        {{ prodcut }} {% if not forloop.last %},{% endif %}
        {% endfor %}
    </p>
    <p>Cart Total: {{ object.cart.total|floatformat:2|localize }}</p>
    <p>Shipping Address: {{ object.shipping_address.get_address|safe }}</p>
    <p>Billing Address: {{ object.billing_address.get_address|safe }}</p>
    <p>Shipping Total: {{ object.shipping_total|floatformat:2|localize }}</p>
    <p>Total: {{ object.order_total|floatformat:2|localize }}</p>
    <form class="form" method="post" action="{% url 'carts:checkout' %}">{% csrf_token %}
        <input type="hidden" name="order_code" value="{{ object.order_code }}">
        <button type="submit" class="btn btn-success">Checkout</button>
    </form>
    {% endif %}
    {% endif %}
</div>


{% endblock %}

templates/carts/home.html
{% extends "base.html" %}
{% load l10n %}

{% block title %}
Cart
{% endblock %}

{% block content %}
<div class="container">
  <h1>Cart</h1>
  {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <div class="alert alert-{% if message.tags %}{{ message.tags }}{% endif %} alert-dismissible fade show"
            role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endfor %}
    </ul>
    {% endif %}
  {% if cart.products.exists %}
  <table class="table cart-table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Component Name</th>
        <th scope="col">Component Price</th>
        <th scope="col">Edit</th>
      </tr>
    </thead>
    <tbody class="cart-body">
      {% for product in cart.products.all %}
      <tr class="cart-products">
        <th scope="row">{{ forloop.counter }}</th>
        <td><a href="{% url 'products:detail' product.slug %}">{{product.title}}</a></td>
        <td>{{ product.price|floatformat:2|localize }} €</td>
        <td>
          {% include "carts/snippets/remove-product.html" with product_id=product.id cart=cart %}
        </td>
      </tr>
      {% endfor %}
      <tr>
        <td colspan="3"></td>
        <td><b>Subtotal: </b> <span class="cart-subTotal">{{ cart.subtotal|floatformat:2|localize }}</span> €</td>
      </tr>
      <tr>
        <td colspan="3"></td>
        <td><b>Total: </b> <span class="cart-total">{{ cart.total|floatformat:2|localize }}</span> €</td>
      </tr>
      <tr>
        <td colspan="3"></td>
        <td><a class="genric-btn info circle btn-block btn-success" href="{% url 'carts:checkout' %}">Checkout</a></td>
      </tr>
    </tbody>
  </table>

  <div class="cart-item-remove-form" style="display: none">
    {% include 'carts/snippets/remove-product.html' %}
  </div>
  {% else %}
  <p class="lead">Cart is empty.</p>
  {% endif %}
</div>
{% endblock %}

{% block bottom %}
{% include 'carts/snippets/cart-ajax.html' %}
{% endblock %}